---
title: "LOO_MRP Simulation Design document"
author: "Swen Kuh"
date: "13/09/2021"
output: html_document
---

This document will describe the simulations we plan to conduct and the expected results from using `loo` and `weighted_loo` to do model comparisons. 

## Description of variables 
Say we want to explore having variables that are **strongly/weakly predictive of the outcome** and **strongly/weakly predictive of the response**. We will have 4 variables $X_1$, $X_2$, $X_3$ and $X_4$, and an outcome $Y$. Lets suppose:

| Variable type                      |  Weakly predictive of the response  |  Strongly predictive of the response |
|:----------------------------------:|:------------------------------------:|:------------------------------------:|
| **Weakly predictive of the outcome**   |        $X_1$                         |        $X_3$                         |
| **Strongly predictive  of the outcome** |        $X_2$                         |        $X_4$                         |


All the $X$'s were sampled unevenly from the population, which gives us strong indication for incorporating inclusion probability in our models. 

We expect $2^4 - 1 = 15$ different models for the combination of these variables. If we ran these models (in `R` syntax):

1) $Y \sim X_1 + X_2 + X_3 + X_4$
2) $Y \sim X_1 + X_2 + X_3$
3) $Y \sim X_1 + X_2 + X_4$
4) $Y \sim X_1 + X_3 + X_4$
5) $Y \sim X_2 + X_3 + X_4$
6) $Y \sim X_1 + X_2$
7) $Y \sim X_1 + X_3$
8) $Y \sim X_1 + X_4$
9) $Y \sim X_2 + X_3$
10) $Y \sim X_2 + X_4$
11) $Y \sim X_3 + X_4$
12) $Y \sim X_1$
13) $Y \sim X_2$
14) $Y \sim X_3$
15) $Y \sim X_4$

## Expected performance
What should we expect? 


